#!/usr/bin/env bash
# Bash script to configure Nginx server with an HTTP header and a redirect rule

sudo apt-get update

sudo apt-get -y install nginx

sudo service nginx start

# Modify the Nginx configuration file with the new lines using sed
sudo export HOSTNAME=$HOSTNAME
sudo sed -i '65i\add_header X-Served-By $HOSTNAME always;' /etc/nginx/sites-available/default

# Reload Nginx configuration
sudo service nginx reload
