#!/usr/bin/env bash
# Script that configures HAProxy on a load balancer

sudo apt-get update -y

# Install software-properties-common (if not installed) for add-apt-repository
apt-get install -y --no-install-recommends software-properties-common

add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get update
apt-get install -y haproxy=2.6.\*

echo "ENABLED=1" >> /etc/default/haproxy

cp /etc/haproxy/haproxy.cfg{,.bak}


printf %s "
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server 455157-web-01 52.91.148.180:80 check
    server 455157-web-02 18.214.87.1:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
