#!/usr/bin/env bash
# install and setup HAproxy
apt update
apt-get -o Dpkg::Options::="--force-confnew" -o Dpkg::Options::="--force-confask" install --reinstall haproxy -y

cat << EOF >> /etc/haproxy/haproxy.cfg
backend web-backend
    balance roundrobin
    server web-01 52.86.171.42:80 check
    server web-02 54.90.41.188:80 check
frontend http
    bind *:80
    mode http

    default_backend web-backend
EOF

service haproxy restart
