#!/bin/bash
# This Bash script adds a NAT (Network Address Translation)rule
# to redirect incoming TCP requests from port 8080 to port 80 using UFW (Uncomplicated Firewall).
# It modifies the /etc/ufw/before.rules file to include the redirection rule, then reloads UFW to apply the changes.

# Redirect incoming requests from port 8080 to port 80
cat <<EOF | sudo tee /etc/ufw/before.rules
*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
COMMIT
EOF

# Reload UFW to apply the changes
sudo ufw reload
