#!/usr/bin/env bash
# Start Apache so as to return a
# page conatining Hello Holberton
# Run Apache on the 265-0 Docker container.
echo "ServerName localhost" >> /etc/apache2.conf
service apache2 start
